sistema/config/routes.rb
Rails.application.routes.draw do
  resources :scores
  resources :bimesters
  devise_for :users
  get 'welcome/index'
  
  resources :students
  resources :groups do
      get 'ticket/index'
  end    
  resources :subjects
  resources :grades
  resources :periods
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sistema/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new
      if user.admin?
          can :manage, :all
      end      
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

sistema/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sistema/app/models/bimester.rb
class Bimester < ApplicationRecord
  belongs_to :period
end

sistema/app/models/grade.rb
class Grade < ApplicationRecord
end

sistema/app/models/group.rb
class Group < ApplicationRecord
  belongs_to :grade
  belongs_to :period
  
  has_many :has_groups
  has_many :students, through: :has_groups
end

sistema/app/models/has_group.rb
class HasGroup < ApplicationRecord
  belongs_to :student
  belongs_to :group
end

sistema/app/models/period.rb
class Period < ApplicationRecord
end

sistema/app/models/score.rb
class Score < ApplicationRecord
  belongs_to :subject
  belongs_to :bimester
  belongs_to :student
end

sistema/app/models/student.rb
class Student < ApplicationRecord
    
  has_many :has_groups
  has_many :groups, :through => :has_groups
end

sistema/app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :grade
end

sistema/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

sistema/app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:grado)
    end
end

sistema/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:matricula, :nombre, :apellido_paterno, :apellido_materno, :nombre_del_tutor, :direccion, :telefono)
    end
end

sistema/app/helpers/application_helper.rb
module ApplicationHelper
end

sistema/app/helpers/bimesters_helper.rb
module BimestersHelper
end

sistema/app/helpers/grades_helper.rb
module GradesHelper
end

sistema/app/helpers/groups_helper.rb
module GroupsHelper
end

sistema/app/helpers/periods_helper.rb
module PeriodsHelper
end

sistema/app/helpers/scores_helper.rb
module ScoresHelper
end

sistema/app/helpers/students_helper.rb
module StudentsHelper
end

sistema/app/helpers/subjects_helper.rb
module SubjectsHelper
end

sistema/app/helpers/ticket_helper.rb
module TicketHelper
end

sistema/app/helpers/welcome_helper.rb
module WelcomeHelper
end

sistema/app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="col-sm-6">
    <div class="card">
        <div class="card-header">
            <strong>Datos del Alumno</strong>
            <small>Formulario</small>
        </div>
        <div class="card-block">
            <div class="form-group">
                <label>Matricula*</label>
                <%= f.text_field :matricula, class: "form-control", placeholder: "Matricula" %>
            </div>
            <div class="form-group">
                <label>Nombre(s)*</label>
                <%= f.text_field :nombre, class: "form-control", placeholder: "Nombre" %>
            </div>
            <div class="form-group">
                <label>Apellido Paterno*</label>
                <%= f.text_field :apellido_paterno, class: "form-control", placeholder: "Apellido Paterno" %>
            </div>
            <div class="form-group">
                <label>Apellido Materno</label>
                <%= f.text_field :apellido_materno, class: "form-control", placeholder: "Apellido Materno" %>
            </div>
            <!--/row-->
        </div>
    </div>
</div>

<div class="col-sm-6">
    <div class="card">
        <div class="card-header">
            <strong>Datos del tutor</strong>
            <small>Formulario</small>
        </div>
        <div class="card-block">
            <div class="form-group">
                <label>Nombre completo*</label>
                <%= f.text_field :nombre_del_tutor, class: "form-control", placeholder: "Nombre Completo" %>
            </div>
            <div class="form-group">
                <label>Dirección*</label>
                <%= f.text_field :direccion, class: "form-control", placeholder: "Direccion" %>
            </div>
            <div class="form-group">
                <label>Telefono*</label>
                <%= f.text_field :telefono, class: "form-control", placeholder: "Telefono" %>
            </div>
            <div class="card-footer">
                <%= f.submit 'Guardar', class: "btn btn-sm btn-primary" %>
                <%= link_to 'Cancelar', students_path, class: "btn btn-sm btn-danger" %>
            </div>
        </div>
    </div>
</div>
<% end %>

sistema/app/views/students/edit.html.erb
<div class="container-fluid">
     <div class="animated fadeIn">
          <div class="row">
            <h1>Editar Alumno</h1>
            <%= render 'form', student: @student %>
         </div>
    </div>
</div>

sistema/app/views/students/index.html.erb
<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row">
            <p id="notice"><%= notice %></p>        
            <div class="col-lg-12">
                <h1>Alumnos</h1>                
                <div class="card">
                    <div class="card-header">
                        <%= link_to 'Registrar Nuevo Alumno', new_student_path, class: "btn btn-primary" %>
                    </div>
                    <div class="card-block">
                        <table class="table table-bordered table-striped table-condensed">
                            <thead>
                                <tr>
                                    <th>Matricula</th>
                                    <th>Nombre</th>
                                    <th>Apellido Paterno</th>
                                    <th>Apellido Materno</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @students.each do |student| %>
                                <tr>
                                    <td><%= student.matricula %></td>
                                    <td><%= student.nombre %></td>
                                    <td><%= student.apellido_paterno %></td>
                                    <td><%= student.apellido_materno %></td>                                
                                    <td><%= link_to student do %>
                                        <button class="btn btn-success"><i class=" fa fa-check"></i></button>
                                        <% end %>
                                    </td>
                                    <td><%= link_to edit_student_path(student) do %>
                                        <button class="btn btn-primary"><i class="fa fa-pencil"></i></button>
                                        <% end %>
                                    </td>
                                    <td><%= link_to student, method: :delete, data: { confirm: '¿Estas seguro?' } do %>
                                        <button class="btn btn-danger"><i class="fa fa-trash-o "></i></button>
                                        <% end %>
                                    </td>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

sistema/app/views/students/new.html.erb
<div class="container-fluid">
     <div class="animated fadeIn">
          <div class="row">
            <h1>Nuevo Alumno</h1>
            <%= render 'form', student: @student %>
         </div>
    </div>
</div>

sistema/app/views/students/show.html.erb
<div class="container-fluid">
     <div class="animated fadeIn">
         <div class="row">
            <p id="notice"><%= notice %></p>
            <div class="col-sm-8 col-md-6">
                <div class="card card-inverse card-primary text-xs-center">
                    <div class="card-header">
                        Alumno
                    </div>
                    <div class="card-blockquote">
                        <p>
                            <strong>Matricula:</strong>
                            <%= @student.matricula %>
                        </p>
                        <p>
                            <strong>Nombre:</strong>
                            <%= @student.nombre %>
                        </p>

                        <p>
                            <strong>Apellido paterno:</strong>
                            <%= @student.apellido_paterno %>
                        </p>

                        <p>
                            <strong>Apellido materno:</strong>
                            <%= @student.apellido_materno %>
                        </p>

                        <p>
                            <strong>Nombre del tutor:</strong>
                            <%= @student.nombre_del_tutor %>
                        </p>

                        <p>
                            <strong>Direccion:</strong>
                            <%= @student.direccion %>
                        </p>

                        <p>
                            <strong>Telefono:</strong>
                            <%= @student.telefono %>
                        </p>
                    </div>
                </div>
            </div>            
         </div>   
         <div class="row">
            <%= link_to 'Editar', edit_student_path(@student), class: "btn btn-sm btn-primary" %>
            <%= link_to 'Cancelar', students_path, class: "btn btn-sm btn-danger" %>
         </div>
    </div>
</div>