sistema/config/routes.rb
Rails.application.routes.draw do
  resources :scores
  resources :bimesters
  devise_for :users
  get 'welcome/index'
  
  resources :students
  resources :groups do
      get 'ticket/index'
  end    
  resources :subjects
  resources :grades
  resources :periods
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sistema/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new
      if user.admin?
          can :manage, :all
      end      
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

sistema/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sistema/app/models/bimester.rb
class Bimester < ApplicationRecord
  belongs_to :period
end

sistema/app/models/grade.rb
class Grade < ApplicationRecord
end

sistema/app/models/group.rb
class Group < ApplicationRecord
  belongs_to :grade
  belongs_to :period
  
  has_many :has_groups
  has_many :students, through: :has_groups
end

sistema/app/models/has_group.rb
class HasGroup < ApplicationRecord
  belongs_to :student
  belongs_to :group
end

sistema/app/models/period.rb
class Period < ApplicationRecord
end

sistema/app/models/score.rb
class Score < ApplicationRecord
  belongs_to :subject
  belongs_to :bimester
  belongs_to :student
end

sistema/app/models/student.rb
class Student < ApplicationRecord
    
  has_many :has_groups
  has_many :groups, :through => :has_groups
end

sistema/app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :grade
end

sistema/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

sistema/app/helpers/bimesters_helper.rb
module BimestersHelper
end

sistema/app/helpers/grades_helper.rb
module GradesHelper
end

sistema/app/helpers/groups_helper.rb
module GroupsHelper
end

sistema/app/helpers/periods_helper.rb
module PeriodsHelper
end

sistema/app/helpers/scores_helper.rb
module ScoresHelper
end

sistema/app/helpers/students_helper.rb
module StudentsHelper
end

sistema/app/helpers/subjects_helper.rb
module SubjectsHelper
end

sistema/app/helpers/ticket_helper.rb
module TicketHelper
end

sistema/app/helpers/welcome_helper.rb
module WelcomeHelper
end

sistema/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Control Escolar</title>    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="navbar-fixed sidebar-nav fixed-nav">
    <%= render partial: 'shared/headbar', locals: { headbar: @shared } %>
    <%= render partial: 'shared/navbar', locals: { navbar: @shared } %>
    <main class="main">
        <div class="container-fluid">
            <%= yield %>
        </div>
    </main>
    <%= render partial: 'shared/footer', locals: { footer: @shared } %>
  </body>
</html>

sistema/app/views/loggin/_loggin.html.erb
 <body class="body-login">
    <p class="notice">
        <%= notice %>
     </p>
    <p class="alert">
        <%= alert %>
     </p>
    <div class="pen-title">
      <h1>Flat Login Form</h1><span>Pen <i class='fa fa-paint-brush'></i> + <i class='fa fa-code'></i> by <a href='http://andytran.me'>Andy Tran</a></span>
    </div>
    <!-- Form Module-->
    <div class="module form-module">
      <div class="toggle"><i class="fa fa-times fa-pencil"></i>
        <div class="tooltip">Click Me</div>
      </div>
      <div class="form">
        <h2>Login to your account</h2>
        <form>
          <input type="text" placeholder="Username"/>
          <input type="password" placeholder="Password"/>
          <button>Login</button>
        </form>
      </div>
      <div class="form">
        <h2>Create an account</h2>
        <form>
          <input type="text" placeholder="Username"/>
          <input type="password" placeholder="Password"/>
          <input type="email" placeholder="Email Address"/>
          <input type="tel" placeholder="Phone Number"/>
          <button>Register</button>
        </form>
      </div>
      <div class="cta"><a href="http://andytran.me">Forgot your password?</a></div>
    </div>
</body>

sistema/app/views/shared/_footer.html.erb
<footer class="footer">
    <span class="text-left">
        Control Escolar © 2016
    </span>
    <span class="float-xs-right">
        Powered by Alesco</a>
    </span>
</footer>

sistema/app/views/shared/_headbar.html.erb
<header class="navbar">
    <div class="container-fluid">                
        <a class="navbar-brand" href="#"></a>
        <ul class="nav navbar-nav hidden-md-down">
            <li class="nav-item">
            </li>
        </ul>        
        <ul class="nav navbar-nav pull-right hidden-md-down">                                
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-   expanded="false">
                <% if user_signed_in? %>
                     <%= image_tag "4.jpg", class: "img-avatar", alt: ""+current_user.email %>
                    <span class="hidden-md-down">:)</span>
                <%else%>
                    <%= image_tag "default.jpg", class: "img-avatar", alt: "inicia sesión"%>
                    <span class="hidden-md-down">:(</span>
                <%end%>
                </a>  
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="dropdown-header text-xs-center">
                        <strong>Cuenta</strong>
                    </div>
                     <% if user_signed_in? %>
                        <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Perfil</a>
                        <a class="dropdown-item" href="#"><i class="fa fa-wrench"></i>editar</a>                        
                        <%=link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do%>
                            <i class="fa fa-user"></i> Cerrar sesión</a>
                        <%end%>
                    <%else%>
                        <%=link_to new_user_session_path, class: "dropdown-item" do%>
                            <i class="fa fa-user"></i> Iniciar Sessión</a>
                        <%end%>
                    <%end%>
                </div>
            </li>
        </ul>
    </div>
</header>


sistema/app/views/shared/_navbar.html.erb
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-item">                
                <%= link_to root_path, class: "nav-link" do%>
                <i class="icon-home icons font-2xl m-t-2"></i> Home
                <%end%>
            </li>
            <% if user_signed_in? %>
                <li class="nav-item">                
                    <%= link_to students_path, class: "nav-link" do%>
                    <i class="icon-graduation icons font-2xl m-t-2"></i> Alumnos
                    <%end%>
                </li>
                <li class="nav-item">                
                    <%= link_to subjects_path, class: "nav-link" do%>
                    <i class="icon-notebook icons font-2xl m-t-2"></i> Materias
                    <%end%>
                </li>
                <li class="nav-item">                
                    <%= link_to groups_path, class: "nav-link" do%>
                    <i class="icon-list icons font-2xl m-t-2"></i> Grupos
                    <%end%>
                </li>
                <li class="nav-item">                
                    <%= link_to grades_path, class: "nav-link" do%>
                    <i class="icon-puzzle icons font-2xl m-t-2"></i> Grados
                    <%end%>
                </li>
                <li class="nav-item">                
                    <%= link_to periods_path, class: "nav-link" do%>
                    <i class="icon-clock icons font-2xl m-t-2"></i> Periodos
                    <%end%>
                </li>
            <%end%>
        </ul>
    </nav>
</div>